Outputs:
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 'myinstance1.PublicIp'
Resources:
  InstanceProfile1:
    Properties:
      InstanceProfileName: someString
      Roles: !Ref 'InstanceRole1'
    Type: AWS::IAM::InstanceProfile
  InstanceRole1:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - codepipeline:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: InstancePolicy1
    Type: AWS::IAM::Role
  SecurityGroup1:
    Properties:
      GroupDescription: Allow NFS over TCP
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: '3000'
          IpProtocol: tcp
          ToPort: '3000'
    Type: AWS::EC2::SecurityGroup
  myinstance1:
    Properties:
      ImageId: ami-083e2c2b01e27ac48
      InstanceType: t1.micro
      SecurityGroups:
        - !Ref 'SecurityGroup1'
      Tags:
        - Key: name
          Value: my_instance1
      UserData: !Base64
        Fn::Join:
          - ''
          - - "#!/bin/bash -xe\n"
            - ./home/ec2-user/cp-board-linux-amd64-0.0.1 &
    Type: AWS::EC2::Instance
